ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_TITLE", "Build Planner")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_DEFAULT_BUILD", "New Build")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_DEFAULT_SETUP", "Base Setup")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_COPIED_BUILD_NAME", "<<1>> Copy")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_COPIED_SETUP_NAME", "<<1>> Copy")
ZO_CreateStringId("SI_BINDING_NAME_GRAVVY_BUILD_PLANNER_TOGGLE", "Open Build Planner")

ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_BUILD", "Build")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SETUP", "Setup")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_NEW", "New")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_RENAME", "Rename")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_COPY", "Copy")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_DELETE", "Delete")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_UNDO", "Undo Delete")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_CLOSE", "Close")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_CANCEL", "Cancel")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SAVE", "Save Slot")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SAVE_NAME", "Save")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_CLEAR", "Clear Slot")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_COPY_MOVE", "Copy / Move")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_COPY_MOVE_TITLE", "Copy or Move Requirement")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_DESTINATION", "Destination")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_MOVE", "Move")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SLOT_EDITOR", "Equipment Requirement")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SET", "Set")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_TYPE", "Type")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_TRAIT", "Trait")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ENCHANTMENT", "Enchantment")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_QUALITY", "Quality")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_LEVEL", "Level")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_CHAMPION_POINTS", "Champion Points")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_LEVEL_DEFAULT", "Level (default <<1>>)")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_CHAMPION_POINTS_DEFAULT", "CP (default <<1>>)")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_LEVEL_VALUE", "Level <<1>>")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_CHAMPION_VALUE", "CP <<1>>")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_NOTES", "Notes")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_DEFAULT", "Setup default")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ITEM_DEFAULT_ENCHANTMENT", "Item default")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_PREVIEW", "Preview: <<1>>")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_PREVIEW_UNAVAILABLE", "Preview unavailable until the set and slot type match.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_PREVIEW_ENCHANTMENT_NOTE", "The preview shows the item's default enchantment; the planned enchantment is <<1>>.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_PREVIEW_LEVEL_NOTE", "The preview could not use the planned <<1>>.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ACQUISITION", "Acquisition: <<1>>")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ACQUISITION_CRAFT", "Craft")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ACQUISITION_GUILD_STORE", "Guild store")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ACQUISITION_RECONSTRUCT", "Reconstruct")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ACQUISITION_BIND_ON_PICKUP", "Bind on pickup")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ACQUISITION_UNKNOWN", "Unknown")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_OWNED_EXACT", "Owned: <<1>>")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_OWNED_NEEDS_WORK", "Owned: <<1>> — adjust <<2>>")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_OWNED_EQUIPPED", "Equipped")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_OWNED_BACKPACK", "Backpack")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_OWNED_BANK", "Bank")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_NEEDS_TRAIT", "trait")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_NEEDS_ENCHANTMENT", "enchantment")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_NEEDS_QUALITY", "quality")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ANY_TYPE", "Any type")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ANY_TRAIT", "Any trait")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_JEWELRY", "Jewelry")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_NOT_PLANNED", "Not planned")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_INCOMPLETE", "Incomplete requirement")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_OCCUPIED", "Used by <<1>>")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SLOT_SAVED", "<<1>> saved.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SLOT_CLEARED", "<<1>> cleared.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SLOT_COPIED", "<<1>> copied to <<2>>.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SLOT_MOVED", "<<1>> moved to <<2>>.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_RESTORED", "Deletion undone.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ENTER_NAME", "Enter a name")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_CONFIRM_DELETE_BUILD", "Delete <<1>> and all of its setups?")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_CONFIRM_DELETE_SETUP", "Delete the <<1>> setup?")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_CONFIRM_REPLACE_SLOT", "Replace the requirement in <<1>>?")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_CONFIRM_TRANSFER_TWO_HAND", "Use <<1>>? Any requirement there will be replaced, and <<2>> will be cleared.")

ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SLOT_HEAD", "Head")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SLOT_SHOULDERS", "Shoulders")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SLOT_CHEST", "Chest")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SLOT_HANDS", "Hands")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SLOT_WAIST", "Waist")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SLOT_LEGS", "Legs")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SLOT_FEET", "Feet")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SLOT_NECK", "Neck")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SLOT_RING1", "Ring 1")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SLOT_RING2", "Ring 2")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SLOT_FRONTMAIN", "Front Bar Main Hand")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SLOT_FRONTOFF", "Front Bar Off Hand")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SLOT_BACKMAIN", "Back Bar Main Hand")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SLOT_BACKOFF", "Back Bar Off Hand")

ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_BUILD_NAME", "Enter a build name.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_BUILD_EXISTS", "A build with that name already exists.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_BUILD_MISSING", "That build no longer exists.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_BUILD_REQUIRED", "At least one build is required.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_SETUP_NAME", "Enter a setup name.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_SETUP_EXISTS", "That build already has a setup with this name.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_SETUP_MISSING", "That setup no longer exists.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_SETUP_REQUIRED", "Each build needs at least one setup.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_SLOT", "That equipment slot is not valid.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_SLOT_OCCUPIED", "A two-handed weapon is using that slot.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_SOURCE_SLOT_EMPTY", "Save this slot before copying or moving it.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_TRANSFER_SLOT", "That requirement cannot be used in the destination slot.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_NO_TRANSFER_SLOT", "There are no compatible destination slots.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_REQUIREMENT", "That equipment requirement is not valid.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_NOTHING_TO_UNDO", "There is nothing to undo.")
