ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_TITLE", "Build Planner")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_DEFAULT_BUILD", "New Build")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_DEFAULT_SETUP", "Base Setup")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_COPIED_BUILD_NAME", "<<1>> Copy")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_COPIED_SETUP_NAME", "<<1>> Copy")

ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_BUILD_NAME", "Enter a build name.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_BUILD_EXISTS", "A build with that name already exists.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_BUILD_MISSING", "That build no longer exists.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_BUILD_REQUIRED", "At least one build is required.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_SETUP_NAME", "Enter a setup name.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_SETUP_EXISTS", "That build already has a setup with this name.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_SETUP_MISSING", "That setup no longer exists.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_SETUP_REQUIRED", "Each build needs at least one setup.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_SLOT", "That equipment slot is not valid.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_SLOT_OCCUPIED", "A two-handed weapon is using that slot.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_REQUIREMENT", "That equipment requirement is not valid.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_NOTHING_TO_UNDO", "There is nothing to undo.")
