ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_TITLE", "Build Planner")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_DEFAULT_BUILD", "New Build")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_DEFAULT_SETUP", "Base Setup")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_COPIED_BUILD_NAME", "<<1>> Copy")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_COPIED_SETUP_NAME", "<<1>> Copy")
ZO_CreateStringId("SI_BINDING_NAME_GRAVVY_BUILD_PLANNER_TOGGLE", "Open Build Planner")

ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_BUILD", "Build")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SETUP", "Setup")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_NEW", "New")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_RENAME", "Rename")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_COPY", "Copy")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_DELETE", "Delete")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_UNDO", "Undo Delete")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_EXPORT", "Shopping List")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_EXPORT_TITLE", "Export Shopping List")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_EXPORT_OWNED", "Owned equipment")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_EXPORT_GLYPHS", "Planned enchantments")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_EXPORT_EXCLUDE", "Skip owned equipment")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_EXPORT_INCLUDE", "Include owned equipment")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_EXPORT_NO_GLYPHS", "Do not add glyphs")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_EXPORT_ADD_GLYPHS", "Add glyphs separately")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_EXPORT_CREATE", "Create List")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_EXPORT_SHOW_CODE", "Show SL2 Code")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_EXPORT_SUMMARY", "<<1>> gear · <<2>> glyphs · <<3>> unavailable · <<4>> owned skipped")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_EXPORT_API_READY", "Shopping List API v2 is ready. Eligible equipment will be added in one batch; lower-quality listings remain valid upgrade candidates.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_EXPORT_API_OLD", "This Shopping List version does not support companion exports. Save the SL2 code, update Shopping List, reload the UI, then import it.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_EXPORT_API_MISSING", "Shopping List is not enabled. Save the SL2 code, install and enable Shopping List, reload the UI, then import it.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_EXPORT_TARGET_QUALITY", "Target <<1>>")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_EXPORT_TARGET_ENCHANTMENT", "Enchant with <<1>>")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_EXPORT_LIST_NOTE", "Build Planner export for <<1>>")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_EXPORT_SOURCE", "Guide: <<1>>")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_EXPORT_GLYPH_NOTE", "Planned enchantment: <<1>>")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_EXPORT_NOTHING", "There is no guild-store equipment to export.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_EXPORT_CREATED", "Created <<1>> with <<2>> entries.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_EXPORT_FAILED", "Shopping List could not create the list: <<1>>")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_EXPORT_CODE_FAILED", "The SL2 code could not be created.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_CODE_TITLE", "Shopping List Code")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_CODE_HELP", "Copy this code somewhere safe. After Shopping List is installed or updated, reload the UI, open Shopping List, and import the code.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_OPEN_ADDON_PAGE", "Open Add-on Page")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_URL_UNAVAILABLE", "ESO could not open the add-on page.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_HELP_TITLE", "Build Planner Help")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_HELP_CONTENT", "ENTERING A GUIDE\nCreate a build for the guide, then create a setup for each gear variation. Pick an equipment slot and start typing the set name. Choose the weight or weapon type, trait, enchantment, quality, and level shown by the guide, then save the slot. Duplicate a setup when only a few pieces change.\n\nITEM PREVIEW\nHover the item icon for ESO's normal tooltip. The preview is representative: a note appears when ESO cannot show the planned enchantment or level directly.\n\nACQUISITION AND PROGRESS\nOwned means an exact equipped, backpack, or bank match. Adjustable means the piece still needs a trait change, enchantment, or quality upgrade. Buy, Craft, Farm, Reconstruct, Transmute, and Unknown describe the available path. When several paths are possible, use Preferred route to keep the one you intend to follow.\n\nSHOPPING LIST\nChoose Shopping List at the top of the planner. The review counts tradeable gear, unavailable gear, and owned pieces skipped by default. You may include owned gear or add planned glyphs as separate entries. Lower-quality gear remains eligible so it can be upgraded later.\n\nIf Shopping List API v2 is enabled, Create List adds the entire batch at once. Otherwise, Show SL2 Code gives you a code to copy. Install or update Shopping List, reload the UI, then import that code from Shopping List. The add-on page button uses ESO's normal external-link confirmation.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_GAMEPAD_EMPTY", "No equipment slots")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_GAMEPAD_EDIT", "Edit Slot")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_GAMEPAD_PREVIOUS_SETUP", "Previous Setup")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_GAMEPAD_NEXT_SETUP", "Next Setup")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_GAMEPAD_PREVIOUS_BUILD", "Previous Build")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_GAMEPAD_NEXT_BUILD", "Next Build")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_GAMEPAD_MANAGE", "Manage")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_GAMEPAD_EDIT_TITLE", "Equipment Requirement")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_GAMEPAD_ARMOR", "Armor")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_GAMEPAD_WEAPON", "Weapon")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_GAMEPAD_MANAGE_TITLE", "Manage Build")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_GAMEPAD_MANAGE_HELP", "Create, rename, reorder, or remove builds and setups.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_GAMEPAD_NEW_BUILD", "New Build")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_GAMEPAD_RENAME_BUILD", "Rename Build")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_GAMEPAD_DUPLICATE_BUILD", "Duplicate Build")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_GAMEPAD_DELETE_BUILD", "Delete Build")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_GAMEPAD_NEW_SETUP", "New Setup")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_GAMEPAD_RENAME_SETUP", "Rename Setup")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_GAMEPAD_DUPLICATE_SETUP", "Duplicate Setup")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_GAMEPAD_MOVE_SETUP_UP", "Move Setup Up")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_GAMEPAD_MOVE_SETUP_DOWN", "Move Setup Down")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_GAMEPAD_DELETE_SETUP", "Delete Setup")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_GAMEPAD_SAVED", "Changes saved.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SETTINGS_ACCESSIBILITY", "Accessibility")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SETTINGS_FONT_SCALE", "Font scale")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SETTINGS_HIGH_CONTRAST", "High contrast")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SETTINGS_HIGH_CONTRAST_TOOLTIP", "Uses black backgrounds and brighter gold borders throughout Build Planner.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SETTINGS_NON_COLOR", "Text status indicators")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SETTINGS_NON_COLOR_TOOLTIP", "Prefixes status messages with Status or Error so they do not rely on color alone.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_STATUS_PREFIX", "Status: <<1>>")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_PREFIX", "Error: <<1>>")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_CLOSE", "Close")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_CANCEL", "Cancel")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SAVE", "Save Slot")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SAVE_NAME", "Save")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_CLEAR", "Clear Slot")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_COPY_MOVE", "Copy / Move")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_COPY_MOVE_TITLE", "Copy or Move Requirement")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_DESTINATION", "Destination")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_MOVE", "Move")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SLOT_EDITOR", "Equipment Requirement")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SET", "Set")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_TYPE", "Type")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_TRAIT", "Trait")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ENCHANTMENT", "Enchantment")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_QUALITY", "Quality")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_LEVEL", "Level")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_CHAMPION_POINTS", "Champion Points")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_LEVEL_DEFAULT", "Level (default <<1>>)")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_CHAMPION_POINTS_DEFAULT", "CP (default <<1>>)")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_LEVEL_VALUE", "Level <<1>>")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_CHAMPION_VALUE", "CP <<1>>")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_NOTES", "Notes")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_DEFAULT", "Setup default")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ITEM_DEFAULT_ENCHANTMENT", "Item default")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_PREVIEW", "Preview: <<1>>")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_PREVIEW_UNAVAILABLE", "Preview unavailable until the set and slot type match.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_PREVIEW_ENCHANTMENT_NOTE", "The preview shows the item's default enchantment; the planned enchantment is <<1>>.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_PREVIEW_LEVEL_NOTE", "The preview could not use the planned <<1>>.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ACQUISITION", "Acquisition: <<1>>")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ACQUISITION_CRAFT", "Craft")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ACQUISITION_GUILD_STORE", "Guild store")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ACQUISITION_RECONSTRUCT", "Reconstruct")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ACQUISITION_BIND_ON_PICKUP", "Bind on pickup")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ACQUISITION_UNKNOWN", "Unknown")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ROUTE", "Preferred route")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ROUTE_AUTOMATIC", "Automatic")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ROUTE_OWNED", "Owned")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ROUTE_BUY", "Buy")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ROUTE_CRAFT", "Craft")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ROUTE_FARM", "Farm")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ROUTE_RECONSTRUCT", "Reconstruct")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ROUTE_TRANSMUTE", "Transmute")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ROUTE_UNKNOWN", "Unknown")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_TRANSMUTE", "Transmute: <<1>>")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_TRANSMUTE_NEEDS_WORK", "Transmute: <<1>> — also adjust <<2>>")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SETUP_PROGRESS", "<<1>>/<<2>> ready · <<3>> adjustable · <<4>> missing")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_OWNED_EXACT", "Owned: <<1>>")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_OWNED_NEEDS_WORK", "Owned: <<1>> — adjust <<2>>")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_OWNED_EQUIPPED", "Equipped")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_OWNED_BACKPACK", "Backpack")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_OWNED_BANK", "Bank")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_NEEDS_TRAIT", "trait")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_NEEDS_ENCHANTMENT", "enchantment")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_NEEDS_QUALITY", "quality")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ANY_TYPE", "Any type")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ANY_TRAIT", "Any trait")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_JEWELRY", "Jewelry")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_NOT_PLANNED", "Not planned")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_INCOMPLETE", "Incomplete requirement")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_OCCUPIED", "Used by <<1>>")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SLOT_SAVED", "<<1>> saved.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SLOT_CLEARED", "<<1>> cleared.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SLOT_COPIED", "<<1>> copied to <<2>>.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SLOT_MOVED", "<<1>> moved to <<2>>.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_RESTORED", "Deletion undone.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ENTER_NAME", "Enter a name")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_CONFIRM_DELETE_BUILD", "Delete <<1>> and all of its setups?")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_CONFIRM_DELETE_SETUP", "Delete the <<1>> setup?")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_CONFIRM_REPLACE_SLOT", "Replace the requirement in <<1>>?")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_CONFIRM_TRANSFER_TWO_HAND", "Use <<1>>? Any requirement there will be replaced, and <<2>> will be cleared.")

ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SLOT_HEAD", "Head")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SLOT_SHOULDERS", "Shoulders")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SLOT_CHEST", "Chest")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SLOT_HANDS", "Hands")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SLOT_WAIST", "Waist")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SLOT_LEGS", "Legs")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SLOT_FEET", "Feet")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SLOT_NECK", "Neck")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SLOT_RING1", "Ring 1")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SLOT_RING2", "Ring 2")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SLOT_FRONTMAIN", "Front Bar Main Hand")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SLOT_FRONTOFF", "Front Bar Off Hand")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SLOT_BACKMAIN", "Back Bar Main Hand")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_SLOT_BACKOFF", "Back Bar Off Hand")

ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_BUILD_NAME", "Enter a build name.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_BUILD_EXISTS", "A build with that name already exists.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_BUILD_MISSING", "That build no longer exists.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_BUILD_REQUIRED", "At least one build is required.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_SETUP_NAME", "Enter a setup name.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_SETUP_EXISTS", "That build already has a setup with this name.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_SETUP_MISSING", "That setup no longer exists.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_SETUP_REQUIRED", "Each build needs at least one setup.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_SLOT", "That equipment slot is not valid.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_SLOT_OCCUPIED", "A two-handed weapon is using that slot.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_SOURCE_SLOT_EMPTY", "Save this slot before copying or moving it.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_TRANSFER_SLOT", "That requirement cannot be used in the destination slot.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_NO_TRANSFER_SLOT", "There are no compatible destination slots.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_REQUIREMENT", "That equipment requirement is not valid.")
ZO_CreateStringId("SI_GRAVVY_BUILD_PLANNER_ERROR_NOTHING_TO_UNDO", "There is nothing to undo.")
