if GetCVar("language.2") ~= "es" then
    return
end

local strings = {
    SI_GRAVVY_BUILD_PLANNER_TITLE = "Planificador de configuraciones",
    SI_GRAVVY_BUILD_PLANNER_DEFAULT_BUILD = "Nueva configuración",
    SI_GRAVVY_BUILD_PLANNER_DEFAULT_SETUP = "Configuración base",
    SI_GRAVVY_BUILD_PLANNER_COPIED_BUILD_NAME = "Copia de <<1>>",
    SI_GRAVVY_BUILD_PLANNER_COPIED_SETUP_NAME = "Copia de <<1>>",
    SI_BINDING_NAME_GRAVVY_BUILD_PLANNER_TOGGLE = "Abrir el planificador de configuraciones",
    SI_GRAVVY_BUILD_PLANNER_BUILD = "Configuración",
    SI_GRAVVY_BUILD_PLANNER_SETUP = "Variante",
    SI_GRAVVY_BUILD_PLANNER_NEW = "Nueva",
    SI_GRAVVY_BUILD_PLANNER_RENAME = "Renombrar",
    SI_GRAVVY_BUILD_PLANNER_COPY = "Copiar",
    SI_GRAVVY_BUILD_PLANNER_DELETE = "Eliminar",
    SI_GRAVVY_BUILD_PLANNER_UNDO = "Deshacer eliminación",
    SI_GRAVVY_BUILD_PLANNER_CLOSE = "Cerrar",
    SI_GRAVVY_BUILD_PLANNER_CANCEL = "Cancelar",
    SI_GRAVVY_BUILD_PLANNER_SAVE = "Guardar espacio",
    SI_GRAVVY_BUILD_PLANNER_SAVE_NAME = "Guardar",
    SI_GRAVVY_BUILD_PLANNER_CLEAR = "Vaciar espacio",
    SI_GRAVVY_BUILD_PLANNER_SLOT_EDITOR = "Requisito de equipo",
    SI_GRAVVY_BUILD_PLANNER_SET = "Conjunto",
    SI_GRAVVY_BUILD_PLANNER_TYPE = "Tipo",
    SI_GRAVVY_BUILD_PLANNER_TRAIT = "Rasgo",
    SI_GRAVVY_BUILD_PLANNER_ENCHANTMENT = "Encantamiento",
    SI_GRAVVY_BUILD_PLANNER_QUALITY = "Calidad",
    SI_GRAVVY_BUILD_PLANNER_LEVEL = "Nivel",
    SI_GRAVVY_BUILD_PLANNER_CHAMPION_POINTS = "Puntos de campeón",
    SI_GRAVVY_BUILD_PLANNER_NOTES = "Notas",
    SI_GRAVVY_BUILD_PLANNER_DEFAULT = "Predeterminado de la variante",
    SI_GRAVVY_BUILD_PLANNER_ANY_TYPE = "Cualquier tipo",
    SI_GRAVVY_BUILD_PLANNER_ANY_TRAIT = "Cualquier rasgo",
    SI_GRAVVY_BUILD_PLANNER_JEWELRY = "Joyería",
    SI_GRAVVY_BUILD_PLANNER_NOT_PLANNED = "Sin planificar",
    SI_GRAVVY_BUILD_PLANNER_INCOMPLETE = "Requisito incompleto",
    SI_GRAVVY_BUILD_PLANNER_OCCUPIED = "Usado por <<1>>",
    SI_GRAVVY_BUILD_PLANNER_SLOT_SAVED = "<<1>> guardado.",
    SI_GRAVVY_BUILD_PLANNER_SLOT_CLEARED = "<<1>> vaciado.",
    SI_GRAVVY_BUILD_PLANNER_RESTORED = "Eliminación deshecha.",
    SI_GRAVVY_BUILD_PLANNER_ENTER_NAME = "Introduce un nombre",
    SI_GRAVVY_BUILD_PLANNER_CONFIRM_DELETE_BUILD = "¿Eliminar <<1>> y todas sus variantes?",
    SI_GRAVVY_BUILD_PLANNER_CONFIRM_DELETE_SETUP = "¿Eliminar la variante <<1>>?",
    SI_GRAVVY_BUILD_PLANNER_SLOT_HEAD = "Cabeza",
    SI_GRAVVY_BUILD_PLANNER_SLOT_SHOULDERS = "Hombros",
    SI_GRAVVY_BUILD_PLANNER_SLOT_CHEST = "Pecho",
    SI_GRAVVY_BUILD_PLANNER_SLOT_HANDS = "Manos",
    SI_GRAVVY_BUILD_PLANNER_SLOT_WAIST = "Cintura",
    SI_GRAVVY_BUILD_PLANNER_SLOT_LEGS = "Piernas",
    SI_GRAVVY_BUILD_PLANNER_SLOT_FEET = "Pies",
    SI_GRAVVY_BUILD_PLANNER_SLOT_NECK = "Cuello",
    SI_GRAVVY_BUILD_PLANNER_SLOT_RING1 = "Anillo 1",
    SI_GRAVVY_BUILD_PLANNER_SLOT_RING2 = "Anillo 2",
    SI_GRAVVY_BUILD_PLANNER_SLOT_FRONTMAIN = "Barra frontal, mano principal",
    SI_GRAVVY_BUILD_PLANNER_SLOT_FRONTOFF = "Barra frontal, mano secundaria",
    SI_GRAVVY_BUILD_PLANNER_SLOT_BACKMAIN = "Barra trasera, mano principal",
    SI_GRAVVY_BUILD_PLANNER_SLOT_BACKOFF = "Barra trasera, mano secundaria",
    SI_GRAVVY_BUILD_PLANNER_ERROR_BUILD_NAME = "Introduce un nombre para la configuración.",
    SI_GRAVVY_BUILD_PLANNER_ERROR_BUILD_EXISTS = "Ya existe una configuración con ese nombre.",
    SI_GRAVVY_BUILD_PLANNER_ERROR_BUILD_MISSING = "Esa configuración ya no existe.",
    SI_GRAVVY_BUILD_PLANNER_ERROR_BUILD_REQUIRED = "Se necesita al menos una configuración.",
    SI_GRAVVY_BUILD_PLANNER_ERROR_SETUP_NAME = "Introduce un nombre para la variante.",
    SI_GRAVVY_BUILD_PLANNER_ERROR_SETUP_EXISTS = "Esta configuración ya contiene una variante con ese nombre.",
    SI_GRAVVY_BUILD_PLANNER_ERROR_SETUP_MISSING = "Esa variante ya no existe.",
    SI_GRAVVY_BUILD_PLANNER_ERROR_SETUP_REQUIRED = "Cada configuración necesita al menos una variante.",
    SI_GRAVVY_BUILD_PLANNER_ERROR_SLOT = "Ese espacio de equipo no es válido.",
    SI_GRAVVY_BUILD_PLANNER_ERROR_SLOT_OCCUPIED = "Un arma de dos manos está usando ese espacio.",
    SI_GRAVVY_BUILD_PLANNER_ERROR_REQUIREMENT = "Ese requisito de equipo no es válido.",
    SI_GRAVVY_BUILD_PLANNER_ERROR_NOTHING_TO_UNDO = "No hay nada que deshacer.",
}

for stringId, translation in pairs(strings) do
    SafeAddString(_G[stringId], translation, 1)
end
