if GetCVar("language.2") ~= "fr" then
    return
end

local strings = {
    SI_GRAVVY_BUILD_PLANNER_TITLE = "Planificateur de configurations",
    SI_GRAVVY_BUILD_PLANNER_DEFAULT_BUILD = "Nouvelle configuration",
    SI_GRAVVY_BUILD_PLANNER_DEFAULT_SETUP = "Configuration de base",
    SI_GRAVVY_BUILD_PLANNER_COPIED_BUILD_NAME = "Copie de <<1>>",
    SI_GRAVVY_BUILD_PLANNER_COPIED_SETUP_NAME = "Copie de <<1>>",
    SI_BINDING_NAME_GRAVVY_BUILD_PLANNER_TOGGLE = "Ouvrir le planificateur de configurations",
    SI_GRAVVY_BUILD_PLANNER_BUILD = "Configuration",
    SI_GRAVVY_BUILD_PLANNER_SETUP = "Variante",
    SI_GRAVVY_BUILD_PLANNER_NEW = "Nouvelle",
    SI_GRAVVY_BUILD_PLANNER_RENAME = "Renommer",
    SI_GRAVVY_BUILD_PLANNER_COPY = "Copier",
    SI_GRAVVY_BUILD_PLANNER_DELETE = "Supprimer",
    SI_GRAVVY_BUILD_PLANNER_UNDO = "Annuler la suppression",
    SI_GRAVVY_BUILD_PLANNER_CLOSE = "Fermer",
    SI_GRAVVY_BUILD_PLANNER_CANCEL = "Annuler",
    SI_GRAVVY_BUILD_PLANNER_SAVE = "Enregistrer l'emplacement",
    SI_GRAVVY_BUILD_PLANNER_SAVE_NAME = "Enregistrer",
    SI_GRAVVY_BUILD_PLANNER_CLEAR = "Vider l'emplacement",
    SI_GRAVVY_BUILD_PLANNER_SLOT_EDITOR = "Équipement requis",
    SI_GRAVVY_BUILD_PLANNER_SET = "Ensemble",
    SI_GRAVVY_BUILD_PLANNER_TYPE = "Type",
    SI_GRAVVY_BUILD_PLANNER_TRAIT = "Trait",
    SI_GRAVVY_BUILD_PLANNER_ENCHANTMENT = "Enchantement",
    SI_GRAVVY_BUILD_PLANNER_QUALITY = "Qualité",
    SI_GRAVVY_BUILD_PLANNER_LEVEL = "Niveau",
    SI_GRAVVY_BUILD_PLANNER_CHAMPION_POINTS = "Points de Champion",
    SI_GRAVVY_BUILD_PLANNER_NOTES = "Notes",
    SI_GRAVVY_BUILD_PLANNER_DEFAULT = "Valeur de la variante",
    SI_GRAVVY_BUILD_PLANNER_ITEM_DEFAULT_ENCHANTMENT = "Enchantement par défaut de l'objet",
    SI_GRAVVY_BUILD_PLANNER_PREVIEW = "Aperçu : <<1>>",
    SI_GRAVVY_BUILD_PLANNER_PREVIEW_UNAVAILABLE = "L'aperçu sera disponible lorsque l'ensemble et le type d'emplacement correspondront.",
    SI_GRAVVY_BUILD_PLANNER_PREVIEW_ENCHANTMENT_NOTE = "L'aperçu montre l'enchantement par défaut de l'objet ; l'enchantement prévu est <<1>>.",
    SI_GRAVVY_BUILD_PLANNER_ANY_TYPE = "N'importe quel type",
    SI_GRAVVY_BUILD_PLANNER_ANY_TRAIT = "N'importe quel trait",
    SI_GRAVVY_BUILD_PLANNER_JEWELRY = "Bijou",
    SI_GRAVVY_BUILD_PLANNER_NOT_PLANNED = "Non planifié",
    SI_GRAVVY_BUILD_PLANNER_INCOMPLETE = "Équipement incomplet",
    SI_GRAVVY_BUILD_PLANNER_OCCUPIED = "Utilisé par <<1>>",
    SI_GRAVVY_BUILD_PLANNER_SLOT_SAVED = "<<1>> enregistré.",
    SI_GRAVVY_BUILD_PLANNER_SLOT_CLEARED = "<<1>> vidé.",
    SI_GRAVVY_BUILD_PLANNER_RESTORED = "Suppression annulée.",
    SI_GRAVVY_BUILD_PLANNER_ENTER_NAME = "Saisissez un nom",
    SI_GRAVVY_BUILD_PLANNER_CONFIRM_DELETE_BUILD = "Supprimer <<1>> et toutes ses variantes ?",
    SI_GRAVVY_BUILD_PLANNER_CONFIRM_DELETE_SETUP = "Supprimer la variante <<1>> ?",
    SI_GRAVVY_BUILD_PLANNER_SLOT_HEAD = "Tête",
    SI_GRAVVY_BUILD_PLANNER_SLOT_SHOULDERS = "Épaules",
    SI_GRAVVY_BUILD_PLANNER_SLOT_CHEST = "Torse",
    SI_GRAVVY_BUILD_PLANNER_SLOT_HANDS = "Mains",
    SI_GRAVVY_BUILD_PLANNER_SLOT_WAIST = "Taille",
    SI_GRAVVY_BUILD_PLANNER_SLOT_LEGS = "Jambes",
    SI_GRAVVY_BUILD_PLANNER_SLOT_FEET = "Pieds",
    SI_GRAVVY_BUILD_PLANNER_SLOT_NECK = "Cou",
    SI_GRAVVY_BUILD_PLANNER_SLOT_RING1 = "Anneau 1",
    SI_GRAVVY_BUILD_PLANNER_SLOT_RING2 = "Anneau 2",
    SI_GRAVVY_BUILD_PLANNER_SLOT_FRONTMAIN = "Barre avant, main principale",
    SI_GRAVVY_BUILD_PLANNER_SLOT_FRONTOFF = "Barre avant, main secondaire",
    SI_GRAVVY_BUILD_PLANNER_SLOT_BACKMAIN = "Barre arrière, main principale",
    SI_GRAVVY_BUILD_PLANNER_SLOT_BACKOFF = "Barre arrière, main secondaire",
    SI_GRAVVY_BUILD_PLANNER_ERROR_BUILD_NAME = "Saisissez un nom de configuration.",
    SI_GRAVVY_BUILD_PLANNER_ERROR_BUILD_EXISTS = "Une configuration porte déjà ce nom.",
    SI_GRAVVY_BUILD_PLANNER_ERROR_BUILD_MISSING = "Cette configuration n'existe plus.",
    SI_GRAVVY_BUILD_PLANNER_ERROR_BUILD_REQUIRED = "Au moins une configuration est requise.",
    SI_GRAVVY_BUILD_PLANNER_ERROR_SETUP_NAME = "Saisissez un nom de variante.",
    SI_GRAVVY_BUILD_PLANNER_ERROR_SETUP_EXISTS = "Cette configuration possède déjà une variante de ce nom.",
    SI_GRAVVY_BUILD_PLANNER_ERROR_SETUP_MISSING = "Cette variante n'existe plus.",
    SI_GRAVVY_BUILD_PLANNER_ERROR_SETUP_REQUIRED = "Chaque configuration nécessite au moins une variante.",
    SI_GRAVVY_BUILD_PLANNER_ERROR_SLOT = "Cet emplacement d'équipement n'est pas valide.",
    SI_GRAVVY_BUILD_PLANNER_ERROR_SLOT_OCCUPIED = "Une arme à deux mains utilise cet emplacement.",
    SI_GRAVVY_BUILD_PLANNER_ERROR_REQUIREMENT = "Cette exigence d'équipement n'est pas valide.",
    SI_GRAVVY_BUILD_PLANNER_ERROR_NOTHING_TO_UNDO = "Il n'y a rien à annuler.",
}

for stringId, translation in pairs(strings) do
    SafeAddString(_G[stringId], translation, 1)
end
